# Generated by Django 5.1.3 on 2024-12-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('qualification', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=2)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('yop', models.DateField()),
                ('course', models.CharField(max_length=40)),
                ('skills', models.CharField(max_length=60)),
                ('mock_rating', models.IntegerField()),
            ],
        ),
    ]
